version: "3.9"

services:
  pocketbase:
    image: arm32v7/pocketbase:latest
    container_name: pocketbase
    command: ["serve", "--http=0.0.0.0:8090"]
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data
      - pb_migrations:/pb_migrations
    restart: unless-stopped

volumes:
  pb_data:
  pb_migrations:
